views/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, UserMixin
from views.file_upload import UPLOAD_FOLDER

# Creating a database object
db = SQLAlchemy()

def create_app():
    # Create a flask application instance
    app = Flask(__name__)

    # This configuration establishes a connection between the database and the flask app
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqldb://end_user:password@localhost:3306/house_hunter'

    # This provides session security and protect against tampering of cookies and other data
    app.config['SECRET_KEY'] = 'bonoko and friends'

        # configuring the upload folder 
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

    # Initialize the database
    db.init_app(app)

    # Import the blueprints from their modules
    from views.routes import  site_views
    from views.sign_up import users_blueprint
    from views.property import property_blueprint
    from views.all_properties import display_all_blueprint
    from views.log_in import login_blueprint
    from views.log_out import logout_blueprint

    # Register the blueprints
    app.register_blueprint(site_views, url_prefix='')
    app.register_blueprint(users_blueprint, url_prefix='')
    app.register_blueprint(property_blueprint, url_prefix='')
    app.register_blueprint(display_all_blueprint, url_prefix='')
    app.register_blueprint(login_blueprint, url_prefix='')
    app.register_blueprint(logout_blueprint, url_prefix='')

    # Create an instance of LoginManager
    login_manager = LoginManager()
    # page to redirect if user is not logged in
    login_manager.login_view = 'site_views.log_in'
    # Initialize the login manager
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        from models.users import User
        return User.query.get(id)

    return app

views/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from models.users import User

# Create a blueprint to handle different routes within the web page
site_views = Blueprint('site_views', __name__, static_folder='static', template_folder='templates', static_url_path='/static')

@site_views.route('/')
@site_views.route('/home/<user_id>')
def home_page(user_id=None):
    user = None
    if user_id is not None:
        user = User.query.get(user_id)
    return render_template('home.html', user=user)

@site_views.route('/houses/<user_id>')
@login_required
def house_page(user_id):
    user = User.query.get(user_id)
    return render_template('House.html', user=current_user, user_id=user_id)

@site_views.route('/about')
def about_page():
    return render_template('about.html', user=None)

@site_views.route('/sign_up')
def sign_page():
    return render_template('sign_up.html', user=None)

@site_views.route('/log-in')
def log_in():
    return render_template('log_in.html', user=None)

@site_views.route('/properties')
def all_properties():
    return render_template('view_properties.html', user=None)

views/templates/House.html
{% extends 'base.html' %}

{% block title %}
    House Page
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" action="{{ url_for('property_blueprint.create_property', user_id=user_id) }}" enctype="multipart/form-data">
                <h1 class="mt-5 mb-4">Add listing:</h1>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Cost:</b>
                        <input type="text" class="form-control" name="cost" placeholder="Cost" pattern="^\d+(?:\.\d{1,2})?$" required>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Rooms:</b>
                        <input type="number" class="form-control" name="rooms" placeholder="Rooms" pattern="^\d+(?:\.\d{1,2})?$" required>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>County:</b>
                        <input type="text" class="form-control" name="county" placeholder="County" required>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Estate:</b>
                        <input type="text" class="form-control" name="estate" placeholder="Estate" required>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Water Availability:</b>
                        <select class="form-select" name="water_availability" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="daily">Daily</option>
                            <option value="irregular">Irregular</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Internet Provider:</b>
                        <select class="form-select" name="internet_provider" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="safaricom">Safaricom</option>
                            <option value="faiba">Faiba</option>
                            <option value="zuku">Zuku</option>
                            <option value="3rd party">3rd party</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Parking:</b>
                        <select class="form-select" name="parking" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="available">Available</option>
                            <option value="not_available">Not available</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Security:</b>
                        <select class="form-select" name="security" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="available">Available</option>
                            <option value="not_available">Not available</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Garbage Collection:</b>
                        <select class="form-select" name="garbage_collection" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="available">Available</option>
                            <option value="not_available">Not available</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Electricity:</b>
                        <select class="form-select" name="electricity" required>
                            <option value="" disabled selected>Select an option</option>
                            <option value="prepaid">Prepaid</option>
                            <option value="postpaid">Postpaid</option>
                        </select>
                    </label>
                </div>

                <div class="mb-3">
                    <label class="form-label">
                        <b>Photo:</b>
                        <input type="file" class="form-control" name="photo" required>
                    </label>
                </div>

                <div class="mt-4">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
        </div>    
    </div>
</div>
{% endblock %}

views/templates/about.html
{% extends 'base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
    <h4><em><strong>Authors:</strong></em></h4>
    <p> Kayongo Samuel Yongo</p>
    <p> Loyd Ngei</p>
    <p> Allan Too</p>

    <h4><em><strong>Description:</strong></em></h4>
    <p> This project was done to fulfil the requirement of our MVP project in ALX. 
        We felt that there was more to be done but with time, we will keep on updating it </P>

    <h4><em><strong>Link to the project's repository:</strong></em></h4>
    <a href="https://github.com/LoydNgei/House-Explorer_Web-App">https://github.com/LoydNgei/House-Explorer_Web-App</a>
        
    <h4><em><strong>Links to our individual Github accounts:</strong></em></h4>
    <a href="https://github.com/KayongoYongo">https://github.com/KayongoYongo</a>
    <br>
    <a href="https://github.com/LoydNgei">https://github.com/LoydNgei</a>
    <br>
    <a href="https://github.com/Kembu">https://github.com/Kembu</a>
{% endblock %}

views/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/styles/BaseStyle.css')}}">
  <script type="text/javascript" src="{{ url_for('static', filename='Javascript/main.js') }}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <title>
    {% block title %}
    
    {% endblock %}
  </title>
</head>
<body>
  <header>
    <a href="{{ url_for('site_views.home_page', user=user) }}">
    <h1>House Explorer</h1>
    </a>
    <p><em>"House Hunting Just Got Real! Dive into the whimsical wonderland of House Explorer and find homes that will make you question reality... or at least your taste in wallpaper!"</em></p>
    <p><em>"To add a listing, the user must be logged in !"</em></p>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{{ url_for('site_views.house_page', user_id=current_user.id) }}">Add Listing</a></li>
          <li><a href="{{ url_for('logout_blueprint.log_out') }}">Log out</a></li>
          <li><a href="{{ url_for('site_views.home_page', user_id=current_user.id) }}">Home page</a></li> 
        {% else %}
          <li><a href="{{ url_for('site_views.about_page') }}">About</a></li>
          <li><a href="{{ url_for('site_views.log_in')}}">Log in</a></li>
          <li><a href="{{ url_for('site_views.sign_page') }}">Sign up</a></li>
          <!--<li><a href="{{ url_for('display_all_blueprint.images', image_files=image_files, user=current_user) }}">View Properties</a></li>-->
        {% endif %}
      </ul>
    </nav>
  </header>

  <main>
    {% block content %}
  
    {% endblock %}
  </main>
  
  <footer>
    <style>
      .footer-container {
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        font-style: italic;
        font-weight: lighter;
      }
      h3 {
        color: darkgoldenrod;
      }

    </style>
    <div class="footer-container">
      <div class="contact-info">
        <h3>Contact</h3>
        <p>Phone: 123-456-7890</p>
        <p>Physical Address: StreetWall Road, Capitano</p>
      </div>
      <div class="address-info">
        <h3>Our Values</h3>
        <p>Transparency</p>
        <p>Comfort</p>
        <p>Security</p>
      </div>
      <div class="social-media">
        <h3>Follow us</h3>
        <ul>
          <a href="https://www.facebook.com" target="_blank" class="fa fa-facebook"></a>
          <a href="https://www.twitter.com" target="_blank" class="fa fa-twitter"></a>
          <a href="https://www.instagram.com" target="_blank" class="fa fa-instagram"></a>
        </ul>        
      </div>
    </div>
  </footer>
</body>
</html>

views/templates/home.html
{% extends 'base.html' %} 

{% block title %}

{% endblock %} 

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/HomeStyle.css')}}">
    <title></title>
  </head>
  <body>

   <style>
        .carousel-item {
            height: 32rem;
            background:#777;
            color: white;
            position: relative;
            background-position: center;
            background-size:cover;
        }

        .container {
        position: absolute;
        bottom: 0;
        left:0;
        right:0;
        padding-bottom:50px;
        }

        .overlay-image {
        position:absolute;
        bottom:0;
        left:0;
        right:0;
        top:0;
        background-position: center;
        background-size: cover;
        }
    </style>
    
    <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="5000">
                <div class="overlay-image" style="background-image:url(/static/Images/Building.jpg)"></div>
                <div class ="container">
                    <h1>Welcome to HouseExplorer</h1>
                    <p>Where we link you to your dream house</p>
                    <a href="{{ url_for('display_all_blueprint.images', image_files=image_files, user=current_user) }}" class="btn btn-lg btn-primary">
                        View properties
                    </a>
                </div>
            </div>

            <div class="carousel-item" data-bs-interval="4000">
                <div class="overlay-image" style="background-image:url(/static/Images/Apartments.jpg)"></div>
                <div class ="container">
                    <h1>Welcome to HouseExplorer</h1>
                    <p>Where we link you to your dream house</p>
                    <a href="{{ url_for('display_all_blueprint.images', image_files=image_files, user=current_user) }}" class="btn btn-lg btn-primary">
                        View properties
                    </a>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="3000">
                <div class="overlay-image" style="background-image:url(/static/Images/Houses.jpg)"></div>
                <div class ="container">
                    <h1>Welcome to HouseExplorer</h1>
                    <p>Where we link you to your dream house</p>
                    <a href="{{ url_for('display_all_blueprint.images', image_files=image_files, user=current_user) }}" class="btn btn-lg btn-primary">
                        View properties
                    </a>
                </div>
            </div>
        </div>
        <a href="#myCarousel" class="carousel-control-prev" role="button" data-bs-slide="prev">
            <span class="sr-only">Previous</span>
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a href="#myCarousel" class="carousel-control-next" role="button" data-bs-slide="next">
            <span class="sr-only">Previous</span>
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
    </div>







    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    {{ error_statement }}
  </body>
</html>

{% endblock %}

views/templates/log_in.html
{% extends 'base.html' %}

{% block title %}
    Log In
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" action="{{ url_for('login_blueprint.login_user') }}" style="color: black;">
                <h1>Log in:</h1>

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="email">
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password_1" placeholder="******">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>

                {% if error_statement %}
                    <div class="alert alert-danger mt-3">{{ error_statement }}</div>
                {% endif %}

                <div class="mt-3">
                    <p>New User? <a href="{{ url_for('site_views.sign_page') }}">Sign Up</a></p>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

views/templates/sign_up.html
{% extends 'base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" action="{{ url_for('users_blueprint.create_user') }}" style="color: black;">
                <h1>Create your Account</h1>

                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="name">
                </div>

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="email">
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password_1" placeholder="******">
                </div>

                <div class="form-group">
                    <label for="confirm-password">Confirm Password:</label>
                    <input type="password" class="form-control" id="confirm-password" name="password_2" placeholder="******">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>

                {% if error_statement %}
                    <div class="alert alert-danger mt-3">{{ error_statement }}</div>
                {% endif %}

                <div class="mt-3">
                    <p>Already registered? <a href="{{ url_for('site_views.log_in') }}">Log In</a></p>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

views/templates/view_properties.html
{% extends 'base.html' %}

{% block title %}
    Property Images
{% endblock %}

{% block content %}
<style>
    .card {
        display: none;
        position: absolute;
        width: 300px;
        padding: 20px;
        background-color: white;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }
    
    .card.show {
        display: block;
    }
</style>

<h1>Properties:</h1>
<div style="display: flex; flex-wrap: wrap;">
    {% for index, filename in image_files|enumerate %}
        <div style="width: 25%; margin-right: 20px; margin-top: 10px; margin-bottom: 10px">
            <a href="#" onclick="showCard({{index}})">
                <img src="{{ url_for('static', filename='UPLOADS/' + filename) }}" width="400" height="300" ;>
            </a>
            <div class="card" id="card{{ index }}">
                <p><strong>Cost:</strong> {{ matching_properties[index].cost }}</p>
                <p><strong>Rooms:</strong> {{ matching_properties[index].rooms }}</p>
                <p><strong>County:</strong> {{ matching_properties[index].county }}</p>
                <p><strong>Estate:</strong> {{ matching_properties[index].estate }}</p>
                <p><strong>Property ID:</strong> {{ matching_properties[index].id }}</p>
                <p><strong>Water availability:</strong> {{ matching_properties[index].water_availability }}</p>
                <p><strong>Electricity:</strong> {{ matching_properties[index].electricity }}</p>
                <p><strong>Internet provider:</strong> {{ matching_properties[index].internet_provider }}</p>
                <p><strong>Garbage collection:</strong> {{ matching_properties[index].garbage_collection }}</p>
                <p><strong>Security:</strong> {{ matching_properties[index].security }}</p>
                <p><strong>Parking:</strong> {{ matching_properties[index].parking }}</p>
                <p><strong>Electricity:</strong> {{ matching_properties[index].electricity }}</p>
            </div>        
        </div>
    {% endfor %}
</div>

<script>
    function showCard(index) {
        var card = document.getElementById('card' + index);
        card.classList.toggle('show');
    }

    // Add event listener to hide cards when clicking outside the image
    document.addEventListener('click', function(event) {
        var target = event.target;
        var isImage = target.tagName === 'IMG';
        var isCard = target.classList.contains('card');

        if (!isImage && !isCard) {
            var cards = document.querySelectorAll('.card');
            cards.forEach(function(card) {
                card.classList.remove('show');
            });
        }
    });
</script>
{% endblock %}